### ISSUE TITLE
Connection problem [solved]

### ISSUE THREAD

**Issue by Roios** [jeffsp/matleap#14]
Hello all

Noob here! So probably a noob question...
I downloaded the last SDK and I would like to play with Leap on Matlab.
I followed the instructions.
The build.m works perfectly. But the rest I have the following error:

test_matleap
**_Invalid MEX-file 'C:\Users\PedroMiguelPires\Desktop\matleap-master\matleap-master\matleap.mexw64': The specified module could not be found._**

Error in matleap_version (line 3)
v=matleap(0);

Error in test_matleap (line 13)
    [version]=matleap_version;

Any idea???

**Comment by Roios** [comment]
Needed to copy a file...I said it was a noob question xD

**Comment by jeffsp** [comment]
Great! Glad you figured it out.
