### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by HiroshanOU** [jeffsp/matleap#8]
how to solve this ,

>> build
Compiling matleap.cpp
Evaluating "mex -I./LeapSDK/include -L./LeapSDK/lib/x64 -lLeap matleap.cpp"
Building with 'Microsoft Visual C++ 2008'.
Error using mex
LINK : fatal error LNK1104: cannot open file 'matleap.mexw64'
Error in build (line 37)
eval(cmd)

**Comment by jeffsp** [comment]
working now with SDK version 2.2.2
